# Generated by Django 5.0.6 on 2024-06-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sports',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
